### PR TITLE
More conversions

### PR DESCRIPTION
**Pull request by arberg**
Thank you for the almost awesome script, and certainly extremely helpful script. I have made it better, adding still more conversions, including map conversions, which turned out to be a bit to crazy to get right, but its nice :). I still miss parenthesis matching, but felt it wasn't worth it. The  `myBlock` -> `named("myBlock")` messed up some source-code I had, but it was easy enough to revert, so not really worth modifying the script for that. Well I would have done it if I knew how to match parentesis in java without coding it myself...

Once again, thanks for the script.

### CODE REVIEW

**Comment by bernaferrari** [comment]
Read awesome!! Thanks a lot!
Just two questions:

Shouldn't Windows people use winget instead of other things? I'm not sure kotlin is available there, but everybody should have access to it.

Second, do you mind updating our test file? It is currently failing, since the output changed. There is a file with the expected output, and github performs the diff on every commit.

**Comment by arberg** [comment]
Ah, tests are a thing. Sounds wise. 

I've added a few more details to the conversion. 

I've updated the test so some of the new stuff is tested, and updated the expected result, as you can see.

Your expected actually contained a bad block with garbled code, due to the bug which duplicated arbitrary sections. That's what happens on quick and dirty copy my output as expected test-result. But its also pretty understandable how that can happen, it kind of did look right on first glance, and any test is still its far better than no test. I tried comparing the input with the output with beyond compare, and it looks reasonable now.

I also tried adding some links in the output, though it kind of sucks to have it there, but it can really help with some good guides, and I stumbled across one such

**Comment by bernaferrari** [comment]
That's great, thanks!

**Comment by arberg** [comment]
Ah, about windows, the winget is still in insider mode, and didn't work for me, maybe because I already had it installed in non-insider variant. Anayway scoop is fine for now for windows users.

**Comment by bernaferrari** [comment]
You once helped me. I refactored the project into this website: https://gradle-kotlin-converter.vercel.app/

**Comment by arberg** [comment]
Thank you Bernardo, looks cool.

I tried it on a java-library gradle file. It's still pretty neat for converting the simple stuff, and cool to have it simply in a url for get it up and running quickly, and interactive as well.

Here are some few lines where it could be improved if you so desire. Though be warned, it could be a huge rabit hole to try to get it all, not that I'm up for that right now. 

This is the input: 
```
plugins {
    id 'java-library'
}
apply from: '../versions.gradle'
apply from: '../config.gradle'
group 'dk.bnr'
version project.file('VERSION-bnr-common').text.trim()

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

println "Target: $target"
```

Which should have given this output if it was to be 'perfect' :

```
plugins {
    id("java-library")
}
apply(from = "../versions.gradle")
apply(from = "../config.gradle")
group = "dk.bnr"
version = project.file("VERSION-bnr-common").readText().trim()

java {
    sourceCompatibility = JavaVersion.VERSION_11  // Set to the desired Java version
    targetCompatibility = JavaVersion.VERSION_11  // Set to the desired Java version
}
```

**Pull request merged**
